"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-10 11:32. Do not edit manually.

Launch config:
  SPLIT_MODE = False
  DATASET_MINING = MERGED
  DATASET_VALIDATION = MERGED
  TIMEFRAMES = ['1H', '4H', '6Hutc', '12Hutc']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['ADAUSDT', 'AVAXUSDT', 'BCHUSDT', 'BNBUSDT', 'DOGEUSDT', 'LINKUSDT', 'NEARUSDT', 'SOLUSDT', 'UNIUSDT', 'XRPUSDT']], '4H': [['ADAUSDT', 'AVAXUSDT', 'BCHUSDT', 'BNBUSDT', 'DOGEUSDT', 'LINKUSDT', 'NEARUSDT', 'SOLUSDT', 'UNIUSDT', 'XRPUSDT']], '6Hutc': [['ADAUSDT', 'AVAXUSDT', 'BCHUSDT', 'BNBUSDT', 'DOGEUSDT', 'LINKUSDT', 'NEARUSDT', 'SOLUSDT', 'UNIUSDT', 'XRPUSDT']], '12Hutc': [['ADAUSDT', 'AVAXUSDT', 'BCHUSDT', 'BNBUSDT', 'DOGEUSDT', 'LINKUSDT', 'NEARUSDT', 'SOLUSDT', 'UNIUSDT', 'XRPUSDT']]}
  PARAM_GRID = {'SELL_AFTER': [50], 'TP_PCT': [6, 8, 10], 'SL_PCT': [6, 8]}
  WFO_WINDOW_CONFIG = {'1H': {'train_months': 9, 'test_months': 2}, '4H': {'train_months': 9, 'test_months': 2}, '6Hutc': {'train_months': 9, 'test_months': 2}, '12Hutc': {'train_months': 9, 'test_months': 2}}
  EMA_ALPHA = 0.3
  PIPELINE_WFO = True
  PIPELINE_CORRELATION = True
  PIPELINE_MULTIVERSE = False
  WFO_NET_GAIN_TH = 30
  WFO_DD_TH = 15
  WFO_R2_TH = 0.8
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.55
  MULTIVERSE_PVALUE_TH = 0.1
  STEPM_K_ESIME = {'1H': 0.02, '4H': 0.02, '6Hutc': 0.02, '12Hutc': 0.02}
  JACCARD_SIMILARITY_TH = 0.8

Train windows:
  12Hutc: 2025-11-14 → 2026-08-14  (9m train)  |  next train: 2026-10-14  (+2m)
  4H    : 2025-11-14 → 2026-08-14  (9m train)  |  next train: 2026-10-14  (+2m)
  6Hutc : 2025-11-14 → 2026-08-14  (9m train)  |  next train: 2026-10-14  (+2m)
  1H    : 2025-11-14 → 2026-08-14  (9m train)  |  next train: 2026-10-14  (+2m)
"""

STRATEGIES = [
    {
        "id": "001280_4H_c01_long_RSI14gt60_AND_HISTVOL20gtSMA_HISTVOL40",
        "symbols": ["ADAUSDT", "AVAXUSDT", "BCHUSDT", "BNBUSDT", "DOGEUSDT", "LINKUSDT", "NEARUSDT", "SOLUSDT", "UNIUSDT", "XRPUSDT"],
        "timeframe": "4H",
        "active": True,
        "direction": "long",
        "specs": [{"type": "rsi", "period": 14, "op": ">", "value": 60}, {"type": "histvol_regime", "period": 20, "op": ">", "sma_period": 40}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "022203_12Hutc_c01_long_RSI7gt60_AND_HISTVOL10gtSMA_HISTVOL30_AND_HISTVOL30ltSMA_HISTVOL40",
        "symbols": ["ADAUSDT", "AVAXUSDT", "BCHUSDT", "BNBUSDT", "DOGEUSDT", "LINKUSDT", "NEARUSDT", "SOLUSDT", "UNIUSDT", "XRPUSDT"],
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "rsi", "period": 7, "op": ">", "value": 60}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 30}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 40}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 6,
    },
    {
        "id": "024772_12Hutc_c01_long_RSI7lt60_AND_HISTVOL10ltSMA_HISTVOL20_AND_HISTVOL10gtSMA_HISTVOL50",
        "symbols": ["ADAUSDT", "AVAXUSDT", "BCHUSDT", "BNBUSDT", "DOGEUSDT", "LINKUSDT", "NEARUSDT", "SOLUSDT", "UNIUSDT", "XRPUSDT"],
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "rsi", "period": 7, "op": "<", "value": 60}, {"type": "histvol_regime", "period": 10, "op": "<", "sma_period": 20}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "027483_1H_c01_long_RSI7gt70_AND_HISTVOL10gtSMA_HISTVOL50_AND_HISTVOL30ltSMA_HISTVOL40",
        "symbols": ["ADAUSDT", "AVAXUSDT", "BCHUSDT", "BNBUSDT", "DOGEUSDT", "LINKUSDT", "NEARUSDT", "SOLUSDT", "UNIUSDT", "XRPUSDT"],
        "timeframe": "1H",
        "active": True,
        "direction": "long",
        "specs": [{"type": "rsi", "period": 7, "op": ">", "value": 70}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 50}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 40}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 6,
    },
    {
        "id": "102727_1H_c01_short_RSI7lt40_AND_HISTVOL30gtSMA_HISTVOL20_AND_HISTVOL30ltSMA_HISTVOL30",
        "symbols": ["ADAUSDT", "AVAXUSDT", "BCHUSDT", "BNBUSDT", "DOGEUSDT", "LINKUSDT", "NEARUSDT", "SOLUSDT", "UNIUSDT", "XRPUSDT"],
        "timeframe": "1H",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 7, "op": "<", "value": 40}, {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 20}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 30}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "107277_6Hutc_c01_short_RSI7lt50_AND_ATR14gtSMA_ATR20_AND_ATR21ltSMA_ATR30",
        "symbols": ["ADAUSDT", "AVAXUSDT", "BCHUSDT", "BNBUSDT", "DOGEUSDT", "LINKUSDT", "NEARUSDT", "SOLUSDT", "UNIUSDT", "XRPUSDT"],
        "timeframe": "6Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 7, "op": "<", "value": 50}, {"type": "atr_regime", "period": 14, "op": ">", "sma_period": 20}, {"type": "atr_regime", "period": 21, "op": "<", "sma_period": 30}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "142800_12Hutc_c01_short_RSI21gt40_AND_ATR14ltSMA_ATR50_AND_HISTVOL10gtSMA_HISTVOL30",
        "symbols": ["ADAUSDT", "AVAXUSDT", "BCHUSDT", "BNBUSDT", "DOGEUSDT", "LINKUSDT", "NEARUSDT", "SOLUSDT", "UNIUSDT", "XRPUSDT"],
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 21, "op": ">", "value": 40}, {"type": "atr_regime", "period": 14, "op": "<", "sma_period": 50}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 30}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 6,
    },
    {
        "id": "168854_4H_c01_short_ATR14ltSMA_ATR30_AND_HISTVOL10ltSMA_HISTVOL40_AND_HISTVOL30gtSMA_HISTVOL30",
        "symbols": ["ADAUSDT", "AVAXUSDT", "BCHUSDT", "BNBUSDT", "DOGEUSDT", "LINKUSDT", "NEARUSDT", "SOLUSDT", "UNIUSDT", "XRPUSDT"],
        "timeframe": "4H",
        "active": True,
        "direction": "short",
        "specs": [{"type": "atr_regime", "period": 14, "op": "<", "sma_period": 30}, {"type": "histvol_regime", "period": 10, "op": "<", "sma_period": 40}, {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 30}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 6,
    },
]
