#quant_d/darwinex/BOT_forex/darwinex/live/strategies.py (forex)
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))
from loguru import logger
from signals.signal_builder import build_signal_fn
from live.mt5_connection import get_rates

# =============================================================================
# COPY ↓
# =============================================================================

"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-03 21:16. Do not edit manually.

Launch config:
  TIMEFRAMES = ['1H', '4H']
  SYMBOLS_BY_TIMEFRAME = {'1H': ['GBPJPY', 'CHFJPY'], '4H': ['EURGBP', 'CHFJPY']}
  PARAM_GRID = {'SELL_AFTER': [50], 'TP_PCT': [0.5, 0.7], 'SL_PCT': [0.5, 0.7]}
  WFO_WINDOW_CONFIG = {'1H': {'train_months': 12, 'test_months': 3}, '4H': {'train_months': 12, 'test_months': 3}}
  EMA_ALPHA = 0.3
  PIPELINE_WFO = True
  PIPELINE_CORRELATION = True
  PIPELINE_MONTECARLO = True
  PIPELINE_MULTIVERSE = True
  WFO_NET_GAIN_TH = 20
  WFO_DD_TH = 10
  WFO_R2_TH = 0.7
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.55
  MONTECARLO_RUIN_TH = 10
  MULTIVERSE_PVALUE_TH = 0.05
  STEPM_K_ESIME = {'1H': 0.05, '4H': 0.05}
  JACCARD_SIMILARITY_TH = 0.8

Train windows:
  4H    : 2025-09-11 → 2026-09-01  (12m train)  |  next train: 2026-12-01  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "000771_4H_long_RSI7lt60_AND_ADX14gt30",
        "symbols"            : ["CHFJPY", "EURGBP"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"type": "rsi", "period": 7, "op": "<", "value": 60},
            {"type": "adx", "period": 14, "op": ">", "value": 30},
        ],
        "sell_after_ncandles": 0,
        "tp_pct"             : 0.5,
        "sl_pct"             : 0.7,
        "lot"                : 0.2,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "053208_4H_long_RSI14lt40_AND_ADX14gt25_AND_HISTVOL30gtSMA_HISTVOL20",
        "symbols"            : ["CHFJPY", "EURGBP"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"type": "rsi", "period": 14, "op": "<", "value": 40},
            {"type": "adx", "period": 14, "op": ">", "value": 25},
            {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 20},
        ],
        "sell_after_ncandles": 0,
        "tp_pct"             : 0.7,
        "sl_pct"             : 0.7,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "061887_4H_long_RSI14lt50_AND_HISTVOL10gtSMA_HISTVOL40_AND_HISTVOL30gtSMA_HISTVOL20",
        "symbols"            : ["CHFJPY", "EURGBP"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"type": "rsi", "period": 14, "op": "<", "value": 50},
            {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 40},
            {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 20},
        ],
        "sell_after_ncandles": 0,
        "tp_pct"             : 0.7,
        "sl_pct"             : 0.7,
        "lot"                : 0.2,
        "magic"              : 3,
        "active"             : True,
    },
]

# =============================================================================
# COPY ↑
# =============================================================================
def get_active_strategies():
    return [s for s in STRATEGIES if s.get("active", True)]


def get_signal(strategy, expected_bar_times):

    timeframe = strategy["timeframe"]
    direction = strategy["direction"]
    signal_fn = build_signal_fn(strategy["specs"], direction)

    results = []

    for symbol, expected_bar_time in expected_bar_times.items():
        try:
            df = get_rates(symbol, timeframe=timeframe, n=500)

            if df.empty:
                logger.error(
                    f"{strategy['id']} | {symbol} | no bars returned | signal dropped"
                )
                results.append({"symbol": symbol, "buy": False, "sell": False})
                continue

            actual_bar_time = int(df.index[-1].timestamp())

            if actual_bar_time != expected_bar_time:
                logger.error(
                    f"{strategy['id']} | {symbol} | bar misalignment | "
                    f"expected={expected_bar_time} actual={actual_bar_time} | "
                    f"signal dropped"
                )
                results.append({"symbol": symbol, "buy": False, "sell": False})
                continue

            arr = {
                "open"  : df["open"].values,
                "high"  : df["high"].values,
                "low"   : df["low"].values,
                "close" : df["close"].values,
                "volume": df["tick_volume"].values,
            }

            signals     = signal_fn(arr, live_trading=True)
            last_signal = int(signals[-1])

            buy  = direction == "long" and last_signal == 1
            sell = direction == "short" and last_signal == -1

            results.append({"symbol": symbol, "buy": buy, "sell": sell})
            logger.info(f"{strategy['id']} | {symbol} | BUY={buy} SELL={sell}")

        except Exception as e:
            logger.error(f"Error in get_signal({strategy['id']}, {symbol}): {e}")
            results.append({"symbol": symbol, "buy": False, "sell": False})

    return results