#quant_miner/darwinex/BOT_forex/darwinex/live/strategies.py (forex)
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))
from loguru import logger
from signals.signal_builder import build_signal_fn
from live.mt5_connection import get_rates

# =============================================================================
# COPY ↓
# =============================================================================

"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-18 13:25. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_MINING = IS
  DATASET_VALIDATION = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['CHFJPY'], ['CHFJPY', 'EURAUD'], ['USDCAD', 'CHFJPY'], ['AUDJPY'], ['AUDJPY', 'CADJPY'], ['AUDJPY', 'CHFJPY'], ['EURJPY', 'AUDJPY']], '4H': [['CHFJPY'], ['CHFJPY', 'EURAUD'], ['EURGBP', 'CHFJPY'], ['GBPJPY', 'CHFJPY'], ['EURJPY', 'GBPJPY'], ['EURJPY', 'CHFJPY'], ['USDJPY', 'CHFJPY'], ['AUDJPY', 'CHFJPY'], ['EURJPY', 'AUDJPY'], ['EURJPY', 'EURCHF'], ['GBPJPY', 'AUDJPY']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [400], 'TP_PCT': [0.78, 1.18, 1.58], 'SL_PCT': [1.18, 1.78, 2.38]}, '4H': {'SELL_AFTER': [0], 'TP_PCT': [1.2, 1.4, 1.6], 'SL_PCT': [1.6, 1.8, 2.0]}}
  WFO_WINDOW_CONFIG = {'1H': {'train_months': 12, 'test_months': 3}, '4H': {'train_months': 12, 'test_months': 3}}
  EMA_ALPHA = 0.3
  PIPELINE_WFO = True
  PIPELINE_CORRELATION = True
  PIPELINE_MULTIVERSE = True
  WFO_NET_GAIN_TH = 5
  WFO_DD_TH = 5
  WFO_R2_TH = 0.7
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.7
  MULTIVERSE_PVALUE_TH = 0.1
  STEPM_K_ESIME = {'1H': 0.001, '4H': 0.001}
  JACCARD_SIMILARITY_TH = 0.9

Train windows:
  1H    : 2025-09-19 → 2026-09-09  (12m train)  |  next train: 2026-12-09  (+3m)
  4H    : 2025-09-19 → 2026-09-09  (12m train)  |  next train: 2026-12-09  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "010053_1H_c01_long_ichimoku_cloud_thickness_tenkan18_kijun26_senkou_b27gt0.4_AND_inertia_rvi40_21ltm0.1",
        "symbols"            : ["CHFJPY"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "ichimoku_cloud_thickness", "params": {"tenkan": 18, "kijun": 26, "senkou_b": 27}, "op": ">", "threshold": 0.4},
            {"indicator": "inertia", "params": {"rvi_period": 40, "period": 21}, "op": "<", "threshold": -0.1},
        ],
        "sell_after_ncandles": 400,
        "tp_pct"             : 1.18,
        "sl_pct"             : 1.18,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "010151_4H_c01_long_ichimoku_cloud_thickness_tenkan18_kijun26_senkou_b27gt0.6_AND_inertia_rvi10_21lt0.1",
        "symbols"            : ["CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "ichimoku_cloud_thickness", "params": {"tenkan": 18, "kijun": 26, "senkou_b": 27}, "op": ">", "threshold": 0.6},
            {"indicator": "inertia", "params": {"rvi_period": 10, "period": 21}, "op": "<", "threshold": 0.1},
        ],
        "sell_after_ncandles": 0,
        "tp_pct"             : 1.6,
        "sl_pct"             : 1.8,
        "lot"                : 0.2,
        "magic"              : 3,
        "active"             : True,
    },
    {
        "id"                 : "011916_1H_c07_long_ichimoku_cloud_thickness_tenkan9_kijun26_senkou_b27gt0.8_AND_donchian_width_20gt0.02",
        "symbols"            : ["AUDJPY", "EURJPY"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "ichimoku_cloud_thickness", "params": {"tenkan": 9, "kijun": 26, "senkou_b": 27}, "op": ">", "threshold": 0.8},
            {"indicator": "donchian_width", "params": {"period": 20}, "op": ">", "threshold": 0.02},
        ],
        "sell_after_ncandles": 400,
        "tp_pct"             : 1.58,
        "sl_pct"             : 2.38,
        "lot"                : 0.2,
        "magic"              : 4,
        "active"             : True,
    },
    {
        "id"                 : "015396_1H_c06_long_trend_intensity_index_15lt30_AND_donchian_width_20gt0.02",
        "symbols"            : ["AUDJPY", "CHFJPY"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "trend_intensity_index", "params": {"period": 15}, "op": "<", "threshold": 30.0},
            {"indicator": "donchian_width", "params": {"period": 20}, "op": ">", "threshold": 0.02},
        ],
        "sell_after_ncandles": 400,
        "tp_pct"             : 1.58,
        "sl_pct"             : 1.78,
        "lot"                : 0.2,
        "magic"              : 6,
        "active"             : True,
    },
]

# =============================================================================
# COPY ↑
# =============================================================================
def get_active_strategies():
    return [s for s in STRATEGIES if s.get("active", True)]


def get_strategy_by_magic(magic: int):
    """Active strategy owning a magic, or None when the magic is unknown."""
    for strategy in get_active_strategies():
        if strategy["magic"] == magic:
            return strategy
    return None


def get_signal(strategy, expected_bar_times):

    timeframe = strategy["timeframe"]
    direction = strategy["direction"]
    signal_fn = build_signal_fn(strategy["specs"], direction)

    results = []

    for symbol, expected_bar_time in expected_bar_times.items():
        try:
            df = get_rates(symbol, timeframe=timeframe, n=500)

            if df.empty:
                logger.error(
                    f"{strategy['id']} | {symbol} | no bars returned | signal dropped"
                )
                results.append({"symbol": symbol, "buy": False, "sell": False})
                continue

            actual_bar_time = int(df.index[-1].timestamp())

            if actual_bar_time != expected_bar_time:
                logger.error(
                    f"{strategy['id']} | {symbol} | bar misalignment | "
                    f"expected={expected_bar_time} actual={actual_bar_time} | "
                    f"signal dropped"
                )
                results.append({"symbol": symbol, "buy": False, "sell": False})
                continue

            arr = {
                "open"  : df["open"].values,
                "high"  : df["high"].values,
                "low"   : df["low"].values,
                "close" : df["close"].values,
                "volume": df["tick_volume"].values,
            }

            signals     = signal_fn(arr, live_trading=True)
            last_signal = int(signals[-1])

            buy  = direction == "long" and last_signal == 1
            sell = direction == "short" and last_signal == -1

            results.append({"symbol": symbol, "buy": buy, "sell": sell})
            logger.info(f"{strategy['id']} | {symbol} | BUY={buy} SELL={sell}")

        except Exception as e:
            logger.error(f"Error in get_signal({strategy['id']}, {symbol}): {e}")
            results.append({"symbol": symbol, "buy": False, "sell": False})

    return results