"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-10-02 15:45. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_IS = IS
  DATASET_OOS = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['GBPJPY'], ['AUDCAD', 'EURAUD'], ['USDJPY', 'EURAUD'], ['USDJPY'], ['EURAUD'], ['AUDCAD', 'EURGBP'], ['USDJPY', 'EURCAD'], ['EURGBP', 'NZDJPY'], ['USDJPY', 'AUDUSD'], ['USDJPY', 'NZDJPY'], ['AUDUSD', 'EURGBP'], ['AUDUSD', 'EURAUD'], ['GBPJPY', 'USDJPY'], ['GBPJPY', 'AUDJPY'], ['AUDJPY', 'EURAUD'], ['GBPJPY', 'EURGBP'], ['GBPJPY', 'EURCAD'], ['EURGBP'], ['EURAUD', 'GBPCAD'], ['USDJPY', 'EURGBP'], ['EURGBP', 'GBPCAD'], ['EURAUD', 'EURCAD'], ['GBPJPY', 'EURAUD'], ['AUDCAD', 'NZDJPY'], ['AUDJPY', 'USDJPY'], ['AUDJPY'], ['AUDJPY', 'EURCAD'], ['NZDJPY'], ['AUDCAD', 'AUDJPY'], ['AUDCAD', 'AUDUSD']], '4H': [['GBPJPY'], ['GBPJPY', 'AUDJPY'], ['AUDJPY', 'EURCAD'], ['GBPJPY', 'AUDCAD'], ['GBPJPY', 'EURCAD'], ['AUDJPY'], ['EURCAD', 'GBPCHF'], ['AUDJPY', 'GBPCHF']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [100], 'TP_PCT': [1.5, 1.5, 1.5], 'SL_PCT': [0.5, 0.5, 0.5]}, '4H': {'SELL_AFTER': [40], 'TP_PCT': [1.0, 1.0, 1.0], 'SL_PCT': [0.5, 0.5, 0.5]}}

Train windows:
  1H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
  4H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "177960_4H_c01_long_hurst_30gt0.6_AND_macd_hist_fast6_slow26_signal9gtm0.4_AND_parkinson_ratio_10gt1.2",
        "symbols"            : ["GBPJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "hurst", "params": {"period": 30}, "op": ">", "threshold": 0.6},
            {"indicator": "macd_hist", "params": {"fast": 6, "slow": 26, "signal": 9}, "op": ">", "threshold": -0.4},
            {"indicator": "parkinson_ratio", "params": {"period": 10}, "op": ">", "threshold": 1.2},
        ],
        "sell_after_ncandles": 40,
        "tp_pct"             : 1.0,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "180286_1H_c02_long_macd_hist_fast6_slow26_signal9ltm0.4_AND_vol_of_vol_10_sma30gt0.4_AND_bb_pctb_slope_5gtm0.05",
        "symbols"            : ["AUDCAD", "EURAUD"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "macd_hist", "params": {"fast": 6, "slow": 26, "signal": 9}, "op": "<", "threshold": -0.4},
            {"indicator": "vol_of_vol", "params": {"period": 10, "sma_period": 30}, "op": ">", "threshold": 0.4},
            {"indicator": "bb_pctb_slope", "params": {"period": 5}, "op": ">", "threshold": -0.05},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.5,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "214560_4H_c01_long_hurst_30gt0.6_AND_rvi_20gtm0.1_AND_parkinson_ratio_10gt1.2",
        "symbols"            : ["GBPJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "hurst", "params": {"period": 30}, "op": ">", "threshold": 0.6},
            {"indicator": "rvi", "params": {"period": 20}, "op": ">", "threshold": -0.1},
            {"indicator": "parkinson_ratio", "params": {"period": 10}, "op": ">", "threshold": 1.2},
        ],
        "sell_after_ncandles": 40,
        "tp_pct"             : 1.0,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 3,
        "active"             : True,
    },
]
