"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-10-05 21:31. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_IS = IS
  DATASET_OOS = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['AUDCAD', 'EURCAD'], ['AUDCAD', 'GBPUSD'], ['AUDCAD', 'GBPCAD'], ['GBPCAD', 'EURGBP'], ['AUDCAD', 'EURJPY'], ['EURGBP', 'USDCAD'], ['EURGBP', 'EURAUD'], ['AUDCAD', 'USDJPY'], ['EURCAD', 'GBPUSD'], ['CHFJPY', 'GBPUSD'], ['GBPCHF', 'EURCAD'], ['GBPCAD', 'EURCAD'], ['EURUSD', 'USDCAD'], ['GBPCAD', 'EURAUD'], ['CHFJPY', 'EURJPY'], ['AUDCAD', 'EURAUD'], ['CHFJPY', 'USDJPY'], ['CHFJPY', 'AUDCAD'], ['GBPCAD', 'AUDJPY'], ['USDJPY', 'AUDJPY'], ['USDJPY', 'GBPUSD'], ['AUDJPY', 'GBPUSD'], ['GBPCAD', 'NZDUSD'], ['EURAUD', 'EURCAD'], ['GBPCAD', 'EURUSD'], ['USDCAD', 'EURCAD'], ['AUDCAD', 'EURGBP'], ['EURUSD', 'EURCAD'], ['EURAUD', 'GBPUSD'], ['GBPJPY', 'EURJPY']], '4H': [['CHFJPY'], ['USDJPY', 'CHFJPY'], ['USDCAD', 'CHFJPY'], ['EURAUD', 'CHFJPY'], ['GBPJPY', 'CHFJPY'], ['GBPJPY'], ['EURJPY', 'CHFJPY'], ['NZDJPY', 'USDCAD'], ['CADJPY', 'CHFJPY'], ['EURCAD', 'CHFJPY'], ['EURGBP', 'GBPCHF'], ['USDCHF', 'GBPJPY'], ['EURCHF', 'USDCAD'], ['USDJPY', 'GBPJPY'], ['NZDJPY', 'CHFJPY'], ['GBPCAD', 'GBPJPY'], ['GBPCHF', 'CHFJPY'], ['AUDJPY', 'USDJPY'], ['AUDCAD', 'USDCHF'], ['GBPJPY', 'USDCAD'], ['USDCAD', 'NZDUSD'], ['USDJPY'], ['GBPJPY', 'NZDUSD'], ['EURJPY', 'AUDCAD'], ['EURJPY', 'CADJPY']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [20], 'TP_PCT': [0.8, 1.0, 1.2], 'SL_PCT': [0.3, 0.5, 0.7]}, '4H': {'SELL_AFTER': [100], 'TP_PCT': [1.3, 1.5, 1.7], 'SL_PCT': [0.3, 0.5, 0.7]}}
  SELECTED_INDICATORS_BY_TIMEFRAME = {'1H': ['ichimoku_tenkan_K', 'ichimoku_price_vs_cloud', 'close_pos_in_bar', 'donchian_pos', 'macd_hist', 'bb_pctb', 'open_close_momentum', 'pivot_dist'], '4H': ['parkinson_ratio', 'bb_pctb', 'ichimoku_price_vs_cloud', 'bb_pctb_slope', 'pivot_dist', 'vortex', 'ppo', 'acceleration', 'close_pos_in_bar']}

Train windows:
  1H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "001625_1H_c01_long_bb_pctb_20gt0.6_AND_pivot_dist_20ltm0.3",
        "symbols"            : ["AUDCAD", "EURCAD"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 20}, "op": ">", "threshold": 0.6},
            {"indicator": "pivot_dist", "params": {"period": 20}, "op": "<", "threshold": -0.3},
        ],
        "sell_after_ncandles": 20,
        "tp_pct"             : 1.0,
        "sl_pct"             : 0.7,
        "lot"                : 1.0,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "004255_1H_c01_long_donchian_pos_7gt0.2_AND_pivot_dist_10ltm1",
        "symbols"            : ["AUDCAD", "EURCAD"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": ">", "threshold": 0.2},
            {"indicator": "pivot_dist", "params": {"period": 10}, "op": "<", "threshold": -1.0},
        ],
        "sell_after_ncandles": 20,
        "tp_pct"             : 1.2,
        "sl_pct"             : 0.7,
        "lot"                : 1.0,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "007844_1H_c07_long_pivot_dist_10ltm1_AND_close_pos_in_bargt0.9",
        "symbols"            : ["EURAUD", "EURGBP"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "pivot_dist", "params": {"period": 10}, "op": "<", "threshold": -1.0},
            {"indicator": "close_pos_in_bar", "params": {}, "op": ">", "threshold": 0.9},
        ],
        "sell_after_ncandles": 20,
        "tp_pct"             : 1.0,
        "sl_pct"             : 0.5,
        "lot"                : 1.0,
        "magic"              : 3,
        "active"             : True,
    },
    {
        "id"                 : "010704_1H_c14_short_bb_pctb_10lt0.4_AND_pivot_dist_10gt0.3",
        "symbols"            : ["EURAUD", "GBPCAD"],
        "timeframe"          : "1H",
        "direction"          : "short",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": "<", "threshold": 0.4},
            {"indicator": "pivot_dist", "params": {"period": 10}, "op": ">", "threshold": 0.3},
        ],
        "sell_after_ncandles": 20,
        "tp_pct"             : 1.0,
        "sl_pct"             : 0.5,
        "lot"                : 1.0,
        "magic"              : 4,
        "active"             : True,
    },
]
