"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-10-06 20:52. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_IS = IS
  DATASET_OOS = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['AUDCAD'], ['CHFJPY', 'AUDCAD'], ['CHFJPY', 'USDCAD'], ['EURCAD', 'EURAUD'], ['USDCAD', 'EURCAD'], ['EURCAD', 'GBPCHF'], ['EURCAD', 'AUDCAD'], ['USDCAD', 'GBPCHF'], ['CHFJPY', 'EURCHF'], ['EURCAD', 'GBPUSD'], ['EURGBP', 'EURCAD'], ['EURGBP', 'GBPUSD'], ['EURUSD', 'EURAUD'], ['EURCAD'], ['EURAUD'], ['AUDCAD', 'GBPCAD'], ['EURGBP', 'AUDCAD'], ['USDCAD', 'GBPUSD'], ['EURUSD', 'EURCAD'], ['EURUSD', 'USDCAD'], ['AUDCAD', 'AUDJPY'], ['EURGBP', 'USDCAD'], ['CHFJPY'], ['EURCAD', 'USDCHF'], ['EURUSD', 'GBPUSD'], ['CHFJPY', 'GBPCHF'], ['EURCAD', 'EURCHF'], ['CHFJPY', 'USDJPY'], ['USDCAD'], ['EURGBP', 'EURAUD']], '4H': [['AUDJPY'], ['AUDJPY', 'GBPCAD'], ['EURJPY']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [20], 'TP_PCT': [0.8, 1.0, 1.2], 'SL_PCT': [0.8, 1.0, 1.2]}, '4H': {'SELL_AFTER': [40], 'TP_PCT': [0.8, 1.0, 1.2], 'SL_PCT': [0.8, 1.0, 1.2]}}
  SELECTED_INDICATORS_BY_TIMEFRAME = {'1H': ['close_pos_in_bar', 'open_close_momentum', 'pivot_dist', 'macd_hist'], '4H': ['inside_outside_ratio']}

Train windows:
  1H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "000188_1H_c03_long_pivot_dist_10ltm0.3_AND_macd_hist_fast12_slow26_signal9gt0.2",
        "symbols"            : ["CHFJPY", "USDCAD"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "pivot_dist", "params": {"period": 10}, "op": "<", "threshold": -0.3},
            {"indicator": "macd_hist", "params": {"fast": 12, "slow": 26, "signal": 9}, "op": ">", "threshold": 0.2},
        ],
        "sell_after_ncandles": 20,
        "tp_pct"             : 0.8,
        "sl_pct"             : 1.0,
        "lot"                : 1.0,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "000452_1H_c21_long_pivot_dist_20ltm0.3_AND_macd_hist_fast12_slow52_signal9gt0.2",
        "symbols"            : ["AUDCAD", "AUDJPY"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "pivot_dist", "params": {"period": 20}, "op": "<", "threshold": -0.3},
            {"indicator": "macd_hist", "params": {"fast": 12, "slow": 52, "signal": 9}, "op": ">", "threshold": 0.2},
        ],
        "sell_after_ncandles": 20,
        "tp_pct"             : 1.0,
        "sl_pct"             : 1.0,
        "lot"                : 1.0,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "000854_1H_c30_long_pivot_dist_10ltm1_AND_close_pos_in_bargt0.9",
        "symbols"            : ["EURAUD", "EURGBP"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "pivot_dist", "params": {"period": 10}, "op": "<", "threshold": -1.0},
            {"indicator": "close_pos_in_bar", "params": {}, "op": ">", "threshold": 0.9},
        ],
        "sell_after_ncandles": 20,
        "tp_pct"             : 1.0,
        "sl_pct"             : 0.8,
        "lot"                : 1.0,
        "magic"              : 3,
        "active"             : True,
    },
]
