"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-30 23:08. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_IS = IS
  DATASET_OOS = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['GBPJPY'], ['AUDCAD', 'EURAUD']], '4H': [['GBPJPY'], ['GBPJPY', 'AUDJPY']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [100], 'TP_PCT': [1.3, 1.5, 1.7], 'SL_PCT': [0.3, 0.5, 0.7]}, '4H': {'SELL_AFTER': [40], 'TP_PCT': [0.8, 1.0, 1.2], 'SL_PCT': [0.3, 0.5, 0.7]}}

Train windows:
  4H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
  1H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "176299_4H_c02_long_donchian_pos_14gt0.6_AND_pivot_dist_10lt0.3_AND_ichimoku_price_vs_cloud_tenkan9_kijun26_senkou_b52lt0.5",
        "symbols"            : ["AUDJPY", "GBPJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_pos", "params": {"period": 14}, "op": ">", "threshold": 0.6},
            {"indicator": "pivot_dist", "params": {"period": 10}, "op": "<", "threshold": 0.3},
            {"indicator": "ichimoku_price_vs_cloud", "params": {"tenkan": 9, "kijun": 26, "senkou_b": 52}, "op": "<", "threshold": 0.5},
        ],
        "sell_after_ncandles": 40,
        "tp_pct"             : 1.2,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "272595_1H_c01_long_ma_dist_20gtm0.6_AND_donchian_pos_14lt0.2_AND_close_pos_in_barlt0.2",
        "symbols"            : ["GBPJPY"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "ma_dist", "params": {"period": 20}, "op": ">", "threshold": -0.6},
            {"indicator": "donchian_pos", "params": {"period": 14}, "op": "<", "threshold": 0.2},
            {"indicator": "close_pos_in_bar", "params": {}, "op": "<", "threshold": 0.2},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.7,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
]
