"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-10-08 21:04. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_IS = IS
  DATASET_OOS = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['GBPCAD', 'EURGBP'], ['EURAUD', 'EURCAD'], ['USDJPY']], '4H': [['USDJPY', 'CHFJPY'], ['CADJPY', 'CHFJPY'], ['CHFJPY'], ['EURJPY', 'CHFJPY'], ['CHFJPY', 'USDCAD'], ['GBPJPY']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [20], 'TP_PCT': [1.3, 1.5, 1.7], 'SL_PCT': [0.3, 0.5, 0.7]}, '4H': {'SELL_AFTER': [100], 'TP_PCT': [1.3, 1.5, 1.7], 'SL_PCT': [0.3, 0.5, 0.7]}}
  SELECTED_INDICATORS_BY_TIMEFRAME = {'1H': ['ichimoku_tenkan_K', 'ichimoku_price_vs_cloud', 'close_pos_in_bar', 'donchian_pos', 'macd_hist', 'pivot_dist', 'bb_pctb_slope', 'close_pct_rank'], '4H': ['bb_pctb', 'ichimoku_price_vs_cloud', 'pivot_dist', 'acceleration', 'close_pos_in_bar', 'rsi', 'donchian_pos', 'open_close_momentum']}

Train windows:
  4H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "116696_4H_c02_long_rsi_7gt60_AND_donchian_pos_21lt0.6_AND_accelerationgtm0.4",
        "symbols"            : ["CADJPY", "CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "rsi", "params": {"period": 7}, "op": ">", "threshold": 60.0},
            {"indicator": "donchian_pos", "params": {"period": 21}, "op": "<", "threshold": 0.6},
            {"indicator": "acceleration", "params": {}, "op": ">", "threshold": -0.4},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.5,
        "lot"                : 1.0,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "228670_4H_c01_long_bb_pctb_10gt0.9_AND_donchian_pos_14lt0.9_AND_close_pos_in_bargt0.8",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.9},
            {"indicator": "donchian_pos", "params": {"period": 14}, "op": "<", "threshold": 0.9},
            {"indicator": "close_pos_in_bar", "params": {}, "op": ">", "threshold": 0.8},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.5,
        "lot"                : 1.0,
        "magic"              : 2,
        "active"             : True,
    },
]
