"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-29 20:45. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_IS = IS
  DATASET_OOS = OOS
  TIMEFRAMES = ['4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['AUDCAD', 'GBPCHF'], ['EURCHF', 'AUDCAD'], ['AUDCAD']], '4H': [['CHFJPY', 'USDCAD'], ['USDJPY', 'CHFJPY'], ['EURAUD', 'CHFJPY'], ['EURJPY', 'CHFJPY'], ['NZDJPY', 'CHFJPY'], ['GBPJPY', 'CHFJPY'], ['CADJPY', 'CHFJPY'], ['EURJPY', 'USDCAD'], ['EURCAD', 'CHFJPY'], ['NZDUSD', 'CHFJPY'], ['GBPJPY', 'USDJPY'], ['NZDJPY', 'GBPJPY'], ['GBPJPY', 'NZDUSD'], ['NZDJPY', 'USDCAD'], ['CHFJPY', 'GBPCAD'], ['AUDUSD', 'USDJPY'], ['USDCHF', 'CHFJPY'], ['EURCHF', 'NZDUSD']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [100], 'TP_PCT': [0.5, 1.0, 1.5], 'SL_PCT': [0.5, 1.0, 1.5]}, '4H': {'SELL_AFTER': [100], 'TP_PCT': [1.3, 1.5, 1.7], 'SL_PCT': [0.3, 0.5, 0.7]}}

Train windows:
  4H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "201685_4H_c02_long_bb_pctb_10gt0.7_AND_donchian_pos_7gt0.8_AND_ichimoku_price_vs_cloud_tenkan9_kijun26_senkou_b52ltm0.5",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.7},
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": ">", "threshold": 0.8},
            {"indicator": "ichimoku_price_vs_cloud", "params": {"tenkan": 9, "kijun": 26, "senkou_b": 52}, "op": "<", "threshold": -0.5},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "211963_4H_c04_long_bb_pctb_10gt0.7_AND_donchian_pos_14lt0.6_AND_accelerationlt0.4",
        "symbols"            : ["CHFJPY", "EURJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.7},
            {"indicator": "donchian_pos", "params": {"period": 14}, "op": "<", "threshold": 0.6},
            {"indicator": "acceleration", "params": {}, "op": "<", "threshold": 0.4},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.5,
        "sl_pct"             : 0.7,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "235749_4H_c04_long_bb_pctb_10gt0.6_AND_donchian_pos_7gt0.6_AND_open_close_momentumltm0.2",
        "symbols"            : ["CHFJPY", "EURJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.6},
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": ">", "threshold": 0.6},
            {"indicator": "open_close_momentum", "params": {}, "op": "<", "threshold": -0.2},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 3,
        "active"             : True,
    },
    {
        "id"                 : "259799_4H_c04_long_bb_pctb_40gt0.2_AND_pivot_dist_40ltm1_AND_accelerationltm0.6",
        "symbols"            : ["CHFJPY", "EURJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 40}, "op": ">", "threshold": 0.2},
            {"indicator": "pivot_dist", "params": {"period": 40}, "op": "<", "threshold": -1.0},
            {"indicator": "acceleration", "params": {}, "op": "<", "threshold": -0.6},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.3,
        "lot"                : 0.2,
        "magic"              : 4,
        "active"             : True,
    },
    {
        "id"                 : "292510_4H_c02_long_bb_pctb_10lt0.6_AND_accelerationlt0.6_AND_open_close_momentumgt0.2",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": "<", "threshold": 0.6},
            {"indicator": "acceleration", "params": {}, "op": "<", "threshold": 0.6},
            {"indicator": "open_close_momentum", "params": {}, "op": ">", "threshold": 0.2},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.5,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 5,
        "active"             : True,
    },
    {
        "id"                 : "304725_4H_c04_long_donchian_pos_7gt0.2_AND_pivot_dist_40ltm1_AND_accelerationltm0.8",
        "symbols"            : ["CHFJPY", "EURJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": ">", "threshold": 0.2},
            {"indicator": "pivot_dist", "params": {"period": 40}, "op": "<", "threshold": -1.0},
            {"indicator": "acceleration", "params": {}, "op": "<", "threshold": -0.8},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 6,
        "active"             : True,
    },
    {
        "id"                 : "331775_4H_c01_long_donchian_pos_7gt0.8_AND_ichimoku_price_vs_cloud_tenkan9_kijun26_senkou_b52lt1_AND_close_pos_in_barlt0.8",
        "symbols"            : ["CHFJPY", "USDCAD"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": ">", "threshold": 0.8},
            {"indicator": "ichimoku_price_vs_cloud", "params": {"tenkan": 9, "kijun": 26, "senkou_b": 52}, "op": "<", "threshold": 1.0},
            {"indicator": "close_pos_in_bar", "params": {}, "op": "<", "threshold": 0.8},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.7,
        "lot"                : 0.2,
        "magic"              : 7,
        "active"             : True,
    },
    {
        "id"                 : "340254_4H_c02_long_donchian_pos_7lt0.9_AND_accelerationlt0.6_AND_open_close_momentumgt0.2",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": "<", "threshold": 0.9},
            {"indicator": "acceleration", "params": {}, "op": "<", "threshold": 0.6},
            {"indicator": "open_close_momentum", "params": {}, "op": ">", "threshold": 0.2},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.5,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 8,
        "active"             : True,
    },
]
