"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-29 21:24. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_IS = IS
  DATASET_OOS = OOS
  TIMEFRAMES = ['4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['AUDCAD', 'GBPCHF'], ['EURCHF', 'AUDCAD'], ['AUDCAD']], '4H': [['USDJPY', 'CHFJPY'], ['CHFJPY'], ['GBPJPY', 'CHFJPY'], ['GBPJPY'], ['GBPJPY', 'USDJPY'], ['EURCHF', 'GBPJPY'], ['EURCHF'], ['USDJPY'], ['EURCHF', 'CHFJPY']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [100], 'TP_PCT': [0.5, 1.0, 1.5], 'SL_PCT': [0.5, 1.0, 1.5]}, '4H': {'SELL_AFTER': [100], 'TP_PCT': [1.3, 1.5, 1.7], 'SL_PCT': [0.3, 0.5, 0.7]}}

Train windows:
  4H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "201269_4H_c01_long_bb_pctb_10gt0.6_AND_donchian_pos_14gt0.6_AND_ichimoku_price_vs_cloud_tenkan9_kijun26_senkou_b52ltm0.5",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.6},
            {"indicator": "donchian_pos", "params": {"period": 14}, "op": ">", "threshold": 0.6},
            {"indicator": "ichimoku_price_vs_cloud", "params": {"tenkan": 9, "kijun": 26, "senkou_b": 52}, "op": "<", "threshold": -0.5},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "201685_4H_c01_long_bb_pctb_10gt0.7_AND_donchian_pos_7gt0.8_AND_ichimoku_price_vs_cloud_tenkan9_kijun26_senkou_b52ltm0.5",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.7},
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": ">", "threshold": 0.8},
            {"indicator": "ichimoku_price_vs_cloud", "params": {"tenkan": 9, "kijun": 26, "senkou_b": 52}, "op": "<", "threshold": -0.5},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "211992_4H_c01_long_bb_pctb_10gt0.7_AND_donchian_pos_14lt0.8_AND_accelerationgtm0.4",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.7},
            {"indicator": "donchian_pos", "params": {"period": 14}, "op": "<", "threshold": 0.8},
            {"indicator": "acceleration", "params": {}, "op": ">", "threshold": -0.4},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 3,
        "active"             : True,
    },
    {
        "id"                 : "212955_4H_c01_long_bb_pctb_10gt0.8_AND_donchian_pos_14lt0.8_AND_accelerationlt0.4",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.8},
            {"indicator": "donchian_pos", "params": {"period": 14}, "op": "<", "threshold": 0.8},
            {"indicator": "acceleration", "params": {}, "op": "<", "threshold": 0.4},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.5,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 4,
        "active"             : True,
    },
    {
        "id"                 : "252027_4H_c01_long_bb_pctb_10gt0.6_AND_pivot_dist_20ltm0.3_AND_accelerationlt0.4",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.6},
            {"indicator": "pivot_dist", "params": {"period": 20}, "op": "<", "threshold": -0.3},
            {"indicator": "acceleration", "params": {}, "op": "<", "threshold": 0.4},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.5,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 5,
        "active"             : True,
    },
    {
        "id"                 : "259807_4H_c02_long_bb_pctb_40gt0.2_AND_pivot_dist_40ltm1_AND_accelerationlt0.8",
        "symbols"            : ["CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 40}, "op": ">", "threshold": 0.2},
            {"indicator": "pivot_dist", "params": {"period": 40}, "op": "<", "threshold": -1.0},
            {"indicator": "acceleration", "params": {}, "op": "<", "threshold": 0.8},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.7,
        "sl_pct"             : 0.7,
        "lot"                : 0.2,
        "magic"              : 6,
        "active"             : True,
    },
    {
        "id"                 : "340254_4H_c01_long_donchian_pos_7lt0.9_AND_accelerationlt0.6_AND_open_close_momentumgt0.2",
        "symbols"            : ["CHFJPY", "USDJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": "<", "threshold": 0.9},
            {"indicator": "acceleration", "params": {}, "op": "<", "threshold": 0.6},
            {"indicator": "open_close_momentum", "params": {}, "op": ">", "threshold": 0.2},
        ],
        "sell_after_ncandles": 100,
        "tp_pct"             : 1.5,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 7,
        "active"             : True,
    },
]
