"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-26 18:24. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_IS = IS
  DATASET_OOS = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['CHFJPY'], ['EURCHF', 'AUDCAD'], ['AUDCAD', 'GBPCHF'], ['USDCAD', 'CHFJPY'], ['USDJPY', 'CHFJPY'], ['CHFJPY', 'EURCAD'], ['CHFJPY', 'AUDCAD'], ['EURGBP', 'GBPCAD'], ['EURCHF'], ['CHFJPY', 'EURAUD'], ['CHFJPY', 'GBPCAD'], ['GBPJPY', 'CHFJPY'], ['EURGBP', 'CHFJPY'], ['EURCHF', 'GBPCHF'], ['AUDCAD'], ['EURGBP', 'AUDCAD'], ['USDCHF', 'AUDCAD'], ['EURCHF', 'GBPCAD'], ['AUDCAD', 'GBPCAD'], ['EURJPY', 'CHFJPY'], ['EURUSD', 'CHFJPY'], ['GBPUSD', 'CHFJPY'], ['AUDUSD', 'CHFJPY'], ['EURGBP', 'GBPCHF'], ['AUDJPY', 'CHFJPY'], ['NZDUSD', 'AUDCAD'], ['CADJPY', 'CHFJPY'], ['NZDUSD', 'EURCHF'], ['AUDUSD', 'EURCHF'], ['NZDUSD', 'GBPCHF']], '4H': [['USDCAD', 'CHFJPY'], ['CHFJPY'], ['USDJPY', 'CHFJPY'], ['EURGBP', 'AUDCAD'], ['EURJPY', 'CHFJPY'], ['EURGBP', 'CHFJPY'], ['CHFJPY', 'AUDCAD'], ['CHFJPY', 'GBPCAD'], ['GBPJPY', 'CHFJPY'], ['EURGBP', 'GBPCAD'], ['EURCHF', 'AUDCAD'], ['CHFJPY', 'EURCAD'], ['USDCHF', 'AUDCAD'], ['AUDCAD', 'GBPCAD'], ['EURJPY', 'GBPCAD'], ['EURGBP', 'EURCHF'], ['EURCHF'], ['CHFJPY', 'EURAUD'], ['AUDCAD'], ['AUDJPY', 'CHFJPY'], ['USDCAD', 'EURJPY'], ['EURJPY', 'AUDCAD'], ['EURUSD', 'CHFJPY'], ['EURCAD', 'AUDCAD'], ['CADJPY', 'CHFJPY'], ['EURJPY', 'EURGBP'], ['GBPJPY', 'AUDJPY'], ['CHFJPY', 'NZDJPY'], ['AUDUSD', 'CHFJPY'], ['EURGBP']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [10, 100], 'TP_PCT': [0.5, 1.0, 1.5], 'SL_PCT': [0.5, 1.0, 1.5]}, '4H': {'SELL_AFTER': [10, 100], 'TP_PCT': [0.5, 1.0, 1.5], 'SL_PCT': [0.5, 1.0, 1.5]}}

Train windows:
  1H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
  4H    : 2025-10-03 → 2026-09-23  (12m train)  |  next train: 2026-12-23  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "000172_4H_c13_long_day_slot_slot5gt0.5",
        "symbols"            : ["AUDCAD", "USDCHF"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "day_slot", "params": {"slot": 5}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 0.5,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "000172_4H_c22_long_day_slot_slot5gt0.5",
        "symbols"            : ["AUDCAD", "EURJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "day_slot", "params": {"slot": 5}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 0.5,
        "sl_pct"             : 1.0,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "002352_1H_c03_long_donchian_pos_7lt0.6_AND_day_slot_slot0gt0.5",
        "symbols"            : ["AUDCAD", "GBPCHF"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": "<", "threshold": 0.6},
            {"indicator": "day_slot", "params": {"slot": 0}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 0.5,
        "sl_pct"             : 1.0,
        "lot"                : 0.2,
        "magic"              : 3,
        "active"             : True,
    },
    {
        "id"                 : "005500_4H_c24_long_ma_dist_50lt0.3_AND_day_slot_slot5gt0.5",
        "symbols"            : ["AUDCAD", "EURCAD"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "ma_dist", "params": {"period": 50}, "op": "<", "threshold": 0.3},
            {"indicator": "day_slot", "params": {"slot": 5}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 1.0,
        "sl_pct"             : 1.0,
        "lot"                : 0.2,
        "magic"              : 4,
        "active"             : True,
    },
    {
        "id"                 : "006852_1H_c24_long_close_pos_in_barlt0.8_AND_day_slot_slot0gt0.5",
        "symbols"            : ["EURGBP", "GBPCHF"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "close_pos_in_bar", "params": {}, "op": "<", "threshold": 0.8},
            {"indicator": "day_slot", "params": {"slot": 0}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 0.5,
        "sl_pct"             : 1.0,
        "lot"                : 0.2,
        "magic"              : 5,
        "active"             : True,
    },
    {
        "id"                 : "008428_4H_c13_long_donchian_pos_7gt0.2_AND_day_slot_slot5gt0.5",
        "symbols"            : ["AUDCAD", "USDCHF"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_pos", "params": {"period": 7}, "op": ">", "threshold": 0.2},
            {"indicator": "day_slot", "params": {"slot": 5}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 0.5,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 6,
        "active"             : True,
    },
    {
        "id"                 : "018434_4H_c11_short_ma_dist_100gt0_AND_day_slot_slot1gt0.5",
        "symbols"            : ["AUDCAD", "EURCHF"],
        "timeframe"          : "4H",
        "direction"          : "short",
        "specs"              : [
            {"indicator": "ma_dist", "params": {"period": 100}, "op": ">", "threshold": 0.0},
            {"indicator": "day_slot", "params": {"slot": 1}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 1.0,
        "sl_pct"             : 1.5,
        "lot"                : 0.2,
        "magic"              : 7,
        "active"             : True,
    },
]
