"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-20 01:37. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_MINING = IS
  DATASET_VALIDATION = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['EURUSD'], ['USDJPY'], ['GBPUSD'], ['AUDUSD'], ['USDCAD'], ['USDCHF'], ['NZDUSD'], ['EURJPY'], ['GBPJPY'], ['EURGBP'], ['EURCHF'], ['AUDJPY'], ['CADJPY'], ['CHFJPY'], ['EURAUD'], ['EURCAD'], ['AUDCAD'], ['GBPCAD'], ['NZDJPY'], ['GBPCHF']], '4H': [['EURUSD'], ['USDJPY'], ['GBPUSD'], ['AUDUSD'], ['USDCAD'], ['USDCHF'], ['NZDUSD'], ['EURJPY'], ['GBPJPY'], ['EURGBP'], ['EURCHF'], ['AUDJPY'], ['CADJPY'], ['CHFJPY'], ['EURAUD'], ['EURCAD'], ['AUDCAD'], ['GBPCAD'], ['NZDJPY'], ['GBPCHF']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [0], 'TP_PCT': [1.5], 'SL_PCT': [1.5]}, '4H': {'SELL_AFTER': [0], 'TP_PCT': [1.5], 'SL_PCT': [1.5]}}
  WFO_WINDOW_CONFIG = {'1H': {'train_months': 12, 'test_months': 3}, '4H': {'train_months': 12, 'test_months': 3}}
  EMA_ALPHA = 0.3
  PIPELINE_WFO = True
  PIPELINE_CORRELATION = True
  PIPELINE_MULTIVERSE = True
  WFO_NET_GAIN_TH = 5
  WFO_DD_TH = 5
  WFO_R2_TH = 0.7
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.7
  MULTIVERSE_PVALUE_TH = 0.1
  STEPM_K_ESIME = {'1H': 0.001, '4H': 0.001}
  JACCARD_SIMILARITY_TH = 0.9

Train windows:
  4H    : 2025-09-19 → 2026-09-09  (12m train)  |  next train: 2026-12-09  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "000544_4H_c14_long_bb_pctb_40lt0.4_AND_hurst_60gt0.5",
        "symbols"            : ["CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 40}, "op": "<", "threshold": 0.4},
            {"indicator": "hurst", "params": {"period": 60}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 0,
        "tp_pct"             : 1.5,
        "sl_pct"             : 1.5,
        "lot"                : 0.2,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "001420_4H_c14_long_bb_pctb_20lt0.4_AND_vol_of_vol_10_sma60gt0.3",
        "symbols"            : ["CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 20}, "op": "<", "threshold": 0.4},
            {"indicator": "vol_of_vol", "params": {"period": 10, "sma_period": 60}, "op": ">", "threshold": 0.3},
        ],
        "sell_after_ncandles": 0,
        "tp_pct"             : 1.5,
        "sl_pct"             : 1.5,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "005749_4H_c14_long_bb_pctb_10gt0.4_AND_swing_leg_ratio_k5lt0.25",
        "symbols"            : ["CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "bb_pctb", "params": {"period": 10}, "op": ">", "threshold": 0.4},
            {"indicator": "swing_leg_ratio", "params": {"k": 5}, "op": "<", "threshold": 0.25},
        ],
        "sell_after_ncandles": 0,
        "tp_pct"             : 1.5,
        "sl_pct"             : 1.5,
        "lot"                : 0.2,
        "magic"              : 3,
        "active"             : True,
    },
    {
        "id"                 : "020251_4H_c14_long_round_level_phase_grid100lt0.1_AND_swing_leg_ratio_k3lt0.5",
        "symbols"            : ["CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "round_level_phase", "params": {"grid": 100}, "op": "<", "threshold": 0.1},
            {"indicator": "swing_leg_ratio", "params": {"k": 3}, "op": "<", "threshold": 0.5},
        ],
        "sell_after_ncandles": 0,
        "tp_pct"             : 1.5,
        "sl_pct"             : 1.5,
        "lot"                : 0.2,
        "magic"              : 4,
        "active"             : True,
    },
    {
        "id"                 : "032489_4H_c20_short_vol_of_vol_10_sma30lt0.3_AND_swing_leg_ratio_k3lt0.25",
        "symbols"            : ["GBPCHF"],
        "timeframe"          : "4H",
        "direction"          : "short",
        "specs"              : [
            {"indicator": "vol_of_vol", "params": {"period": 10, "sma_period": 30}, "op": "<", "threshold": 0.3},
            {"indicator": "swing_leg_ratio", "params": {"k": 3}, "op": "<", "threshold": 0.25},
        ],
        "sell_after_ncandles": 0,
        "tp_pct"             : 1.5,
        "sl_pct"             : 1.5,
        "lot"                : 0.2,
        "magic"              : 5,
        "active"             : True,
    },
]
