"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-19 15:20. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_MINING = IS
  DATASET_VALIDATION = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['CHFJPY'], ['CHFJPY', 'EURAUD'], ['USDCAD', 'CHFJPY'], ['AUDJPY'], ['AUDJPY', 'CADJPY'], ['AUDJPY', 'CHFJPY'], ['EURJPY', 'AUDJPY']], '4H': [['CHFJPY'], ['CHFJPY', 'EURAUD'], ['EURGBP', 'CHFJPY'], ['GBPJPY', 'CHFJPY'], ['EURJPY', 'GBPJPY'], ['EURJPY', 'CHFJPY'], ['USDJPY', 'CHFJPY'], ['AUDJPY', 'CHFJPY'], ['EURJPY', 'AUDJPY'], ['EURJPY', 'EURCHF'], ['GBPJPY', 'AUDJPY']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [10], 'TP_PCT': [200], 'SL_PCT': [200]}, '4H': {'SELL_AFTER': [10], 'TP_PCT': [200], 'SL_PCT': [200]}}
  WFO_WINDOW_CONFIG = {'1H': {'train_months': 12, 'test_months': 3}, '4H': {'train_months': 12, 'test_months': 3}}
  EMA_ALPHA = 0.3
  PIPELINE_WFO = True
  PIPELINE_CORRELATION = True
  PIPELINE_MULTIVERSE = True
  WFO_NET_GAIN_TH = 5
  WFO_DD_TH = 5
  WFO_R2_TH = 0.7
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.7
  MULTIVERSE_PVALUE_TH = 0.1
  STEPM_K_ESIME = {'1H': 0.001, '4H': 0.001}
  JACCARD_SIMILARITY_TH = 0.9

Train windows:
  4H    : 2025-09-19 → 2026-09-09  (12m train)  |  next train: 2026-12-09  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "001401_4H_c06_long_ichimoku_cloud_thickness_tenkan18_kijun26_senkou_b27gt0.6_AND_trend_intensity_index_30lt30",
        "symbols"            : ["CHFJPY", "EURJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "ichimoku_cloud_thickness", "params": {"tenkan": 18, "kijun": 26, "senkou_b": 27}, "op": ">", "threshold": 0.6},
            {"indicator": "trend_intensity_index", "params": {"period": 30}, "op": "<", "threshold": 30.0},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 200,
        "sl_pct"             : 200,
        "lot"                : 0.2,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "003669_4H_c06_long_ichimoku_cloud_thickness_tenkan9_kijun13_senkou_b27gt0.4_AND_rvi_40ltm0.1",
        "symbols"            : ["CHFJPY", "EURJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "ichimoku_cloud_thickness", "params": {"tenkan": 9, "kijun": 13, "senkou_b": 27}, "op": ">", "threshold": 0.4},
            {"indicator": "rvi", "params": {"period": 40}, "op": "<", "threshold": -0.1},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 200,
        "sl_pct"             : 200,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
]
