"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-09-24 22:05. Do not edit manually.

Launch config:
  SPLIT_MODE = True
  DATASET_IS = IS
  DATASET_OOS = OOS
  TIMEFRAMES = ['1H', '4H']
  SYMBOL_COMBOS_BY_TIMEFRAME = {'1H': [['CHFJPY', 'AUDCAD'], ['CHFJPY'], ['CHFJPY', 'EURCAD'], ['EURCHF', 'AUDCAD'], ['EURGBP', 'CHFJPY'], ['AUDCAD', 'GBPCHF'], ['EURUSD', 'CHFJPY'], ['CHFJPY', 'EURAUD'], ['AUDUSD', 'CHFJPY'], ['EURJPY', 'CHFJPY']], '4H': [['CHFJPY'], ['EURJPY', 'CHFJPY'], ['CHFJPY', 'EURCAD'], ['USDCAD', 'CHFJPY'], ['GBPJPY', 'CHFJPY'], ['CHFJPY', 'EURAUD'], ['CHFJPY', 'AUDCAD'], ['CHFJPY', 'GBPCAD'], ['EURGBP', 'CHFJPY'], ['USDJPY', 'CHFJPY']]}
  PARAM_GRID_BY_TIMEFRAME = {'1H': {'SELL_AFTER': [10, 100], 'TP_PCT': [0.5, 1.0, 1.5], 'SL_PCT': [0.5, 1.0, 1.5]}, '4H': {'SELL_AFTER': [10, 100], 'TP_PCT': [0.5, 1.0, 1.5], 'SL_PCT': [0.5, 1.0, 1.5]}}

Train windows:
  4H    : 2025-09-19 → 2026-09-09  (12m train)  |  next train: 2026-12-09  (+3m)
  1H    : 2025-09-19 → 2026-09-09  (12m train)  |  next train: 2026-12-09  (+3m)
"""

STRATEGIES = [
    {
        "id"                 : "001796_4H_c08_long_accelerationgtm0.8_AND_day_slot_slot5gt0.5",
        "symbols"            : ["CHFJPY", "GBPCAD"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "acceleration", "params": {}, "op": ">", "threshold": -0.8},
            {"indicator": "day_slot", "params": {"slot": 5}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 0.5,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 1,
        "active"             : True,
    },
    {
        "id"                 : "001820_4H_c07_long_accelerationgtm0.6_AND_day_slot_slot5gt0.5",
        "symbols"            : ["AUDCAD", "CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "acceleration", "params": {}, "op": ">", "threshold": -0.6},
            {"indicator": "day_slot", "params": {"slot": 5}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 1.0,
        "sl_pct"             : 1.0,
        "lot"                : 0.2,
        "magic"              : 2,
        "active"             : True,
    },
    {
        "id"                 : "003896_4H_c07_long_rvi_10lt0.1_AND_day_slot_slot5gt0.5",
        "symbols"            : ["AUDCAD", "CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "rvi", "params": {"period": 10}, "op": "<", "threshold": 0.1},
            {"indicator": "day_slot", "params": {"slot": 5}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 1.0,
        "sl_pct"             : 1.0,
        "lot"                : 0.2,
        "magic"              : 3,
        "active"             : True,
    },
    {
        "id"                 : "006128_1H_c06_long_pivot_dist_40lt0.3_AND_day_slot_slot0gt0.5",
        "symbols"            : ["AUDCAD", "GBPCHF"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "pivot_dist", "params": {"period": 40}, "op": "<", "threshold": 0.3},
            {"indicator": "day_slot", "params": {"slot": 0}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 0.5,
        "sl_pct"             : 1.0,
        "lot"                : 0.2,
        "magic"              : 4,
        "active"             : True,
    },
    {
        "id"                 : "006152_4H_c07_long_donchian_width_10lt0.01_AND_day_slot_slot5gt0.5",
        "symbols"            : ["AUDCAD", "CHFJPY"],
        "timeframe"          : "4H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_width", "params": {"period": 10}, "op": "<", "threshold": 0.01},
            {"indicator": "day_slot", "params": {"slot": 5}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 1.0,
        "sl_pct"             : 0.5,
        "lot"                : 0.2,
        "magic"              : 5,
        "active"             : True,
    },
    {
        "id"                 : "009440_1H_c06_long_donchian_width_40lt0.01_AND_day_slot_slot0gt0.5",
        "symbols"            : ["AUDCAD", "GBPCHF"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "donchian_width", "params": {"period": 40}, "op": "<", "threshold": 0.01},
            {"indicator": "day_slot", "params": {"slot": 0}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 1.0,
        "sl_pct"             : 1.0,
        "lot"                : 0.2,
        "magic"              : 6,
        "active"             : True,
    },
    {
        "id"                 : "009896_1H_c06_long_close_pos_in_barlt0.8_AND_day_slot_slot0gt0.5",
        "symbols"            : ["AUDCAD", "GBPCHF"],
        "timeframe"          : "1H",
        "direction"          : "long",
        "specs"              : [
            {"indicator": "close_pos_in_bar", "params": {}, "op": "<", "threshold": 0.8},
            {"indicator": "day_slot", "params": {"slot": 0}, "op": ">", "threshold": 0.5},
        ],
        "sell_after_ncandles": 10,
        "tp_pct"             : 1.0,
        "sl_pct"             : 1.0,
        "lot"                : 0.2,
        "magic"              : 7,
        "active"             : True,
    },
]
