#core/rule_mining/rule_writter.py
import os
import logging
from datetime import datetime
import pandas as pd
from setup.config_core import settings
from pipeline.wfo import INNER_N_JOBS, WFO_WINDOW_CONFIG
from runs.run_deploy import run_wfo_deploy_ema

logger = logging.getLogger("BOT_batch.rule_mining.writter")


def _fmt_spec(spec: dict) -> str:
    params_str = ", ".join(f'"{k}": {v}' for k, v in spec["params"].items())
    return (
        f'{{"indicator": "{spec["indicator"]}", "params": {{{params_str}}}, '
        f'"op": "{spec["op"]}", "threshold": {spec["threshold"]}}}'
    )

def _fmt_custom_value(value, index: int) -> str:
    if value == "AUTO_INCREMENT":
        return str(index)
    if isinstance(value, str):
        return f'"{value}"'
    return str(value)


def _build_window_summary_lines(deploy_map: dict) -> list:
    seen_tfs = {}
    lines    = []

    for entry in deploy_map.values():
        tf = entry.get("timeframe")
        if tf is None or tf in seen_tfs:
            continue
        seen_tfs[tf] = True

        ts = entry.get("train_start_ts")
        te = entry.get("train_end_ts")
        if ts is None or te is None:
            continue

        wfo_cfg     = WFO_WINDOW_CONFIG.get(tf, {})
        train_m     = wfo_cfg.get("train_months")
        test_m      = wfo_cfg.get("test_months")
        ts_str      = pd.Timestamp(ts).strftime("%Y-%m-%d")
        te_str      = pd.Timestamp(te).strftime("%Y-%m-%d")
        next_str    = (pd.Timestamp(te) + pd.DateOffset(months=int(test_m))).strftime("%Y-%m-%d") if test_m is not None else "?"
        train_m_str = f"{int(train_m)}m train" if train_m is not None else "?m train"
        test_m_str  = f"+{int(test_m)}m" if test_m is not None else "?"

        lines.append(f'  {tf:<6}: {ts_str} → {te_str}  ({train_m_str})  |  next train: {next_str}  ({test_m_str})')

    return lines


def _build_strategy_lines(rule_id: str, entry: dict, index: int, key_width: int) -> list:
    lines       = []
    symbols_str = ", ".join(f'"{sym}"' for sym in entry["symbols"])

    def kv(key: str, value: str) -> str:
        return f'        "{key}"{" " * (key_width - len(key))}: {value},'

    lines.append("    {")
    lines.append(kv("id", f'"{rule_id}"'))
    lines.append(kv("symbols", f'[{symbols_str}]'))
    lines.append(kv("timeframe", f'"{entry["timeframe"]}"'))
    lines.append(kv("direction", f'"{entry["side"]}"'))
    lines.append(f'        "specs"{" " * (key_width - 5)}: [')
    for s in entry["specs"]:
        lines.append(f'            {_fmt_spec(s)},')
    lines.append('        ],')
    lines.append(kv("sell_after_ncandles", str(entry["params"]["SELL_AFTER"])))
    lines.append(kv("tp_pct", str(entry["params"]["TP_PCT"])))
    lines.append(kv("sl_pct", str(entry["params"]["SL_PCT"])))
    for field_name, field_value in settings.CUSTOM_FIELDS.items():
        lines.append(kv(field_name, _fmt_custom_value(field_value, index)))
    lines.append(kv("active", str(entry["approved"])))
    lines.append("    },")

    return lines


def save_rule_deploy_batch(
    output_path: str,
    deploy_map: dict,
    run_config: dict = None,
) -> None:

    lines = [
        '"""',
        'Rule Mining Strategies Configuration — Deploy',
        '',
        f'Auto-generated by run_deploy_rule on {datetime.now().strftime("%Y-%m-%d %H:%M")}. Do not edit manually.',
    ]

    if run_config:
        lines += ['', 'Launch config:']
        lines += [f'  {k} = {v}' for k, v in run_config.items()]

    window_lines = _build_window_summary_lines(deploy_map)
    if window_lines:
        lines += ['', 'Train windows:'] + window_lines

    lines += ['"""', '', 'STRATEGIES = [']

    sorted_ids = sorted(deploy_map.keys(), key=lambda rid: int(rid.split("_")[0]))

    fixed_keys = ["id", "symbols", "timeframe", "direction", "specs",
                  "sell_after_ncandles", "tp_pct", "sl_pct", "active"]
    key_width  = max(len(k) for k in fixed_keys + list(settings.CUSTOM_FIELDS.keys()))

    for index, rule_id in enumerate(sorted_ids, start=1):
        entry = deploy_map[rule_id]
        lines += _build_strategy_lines(rule_id, entry, index, key_width)

    lines.append("]")

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    logger.info(f"DEPLOY ── rule mining batch saved → {output_path}")


def run_deploy_rule(
    rule_id: str,
    specs: list,
    side: str,
    ohlcv_is: dict,
    signal_fn: callable,
    param_grid: dict,
    order_amount: int,
    timeframe: str,
    approved: bool,
    deploy_map: dict,
    label_width: int = 0,
) -> None:

    label = f"{rule_id:<{label_width}}"

    deploy_params, deploy_symbols, train_start_ts, train_end_ts = run_wfo_deploy_ema(
        ohlcv_is     = ohlcv_is,
        timeframe    = timeframe,
        param_grid   = param_grid,
        signal_fn    = signal_fn,
        order_amount = order_amount,
        n_jobs       = INNER_N_JOBS,
    )
    params_str   = " | ".join(f"{k}={v}" for k, v in deploy_params.items() if k != "SELL_AFTER")
    status       = "🟢 active" if approved else "🔴 inactive"
    ts_start_str = pd.Timestamp(train_start_ts).strftime("%Y-%m-%d")
    ts_end_str   = pd.Timestamp(train_end_ts).strftime("%Y-%m-%d")
    logger.info(
        f"DEPLOY  ── {label} ── {status} | {params_str} | "
        f"{len(deploy_symbols):>3} symbols | {ts_start_str} → {ts_end_str}"
    )

    deploy_map[rule_id] = {
        "specs":          specs,
        "side":           side,
        "timeframe":      timeframe,
        "params":         deploy_params,
        "approved":       approved,
        "symbols":        deploy_symbols,
        "train_start_ts": train_start_ts,
        "train_end_ts":   train_end_ts,
    }
